### ISSUE TITLE
Replace Jar File

### ISSUE THREAD

**Issue by UnderSampled** [itkach/slobber#1]
I am currently trying to get Aard2 to release in the F-Droid app repository. I actually learned about Aard through F-Droid, so I really want to get it back in. I have made a repository for ease of building the app: https://gitlab.com/UnderSampled/aard2-build

This actually works pretty well, but I also need to make sure the source is clean. The main issue is with the simple framework Jar, which I know is open source but would like to verify, preferably by building it along with the rest of the system. Do you have the original patch for it? I can put it along side and compile it like slobj is, but I also could not find the 1.5.1.7 version you used -- so I would need you to confirm a different version for use. Alternatively you could provide the source to build with maven that you used. We could also fork their newer github repository and make whatever changes are necessary there.

**Comment by itkach** [comment]
The patched source is here: https://github.com/itkach/slobber/blob/master/libs/simple-5.1.7.1-sources.itkach.jar

As far as I can tell nothing changed in the source code since then, so original source for 5.1.7.1 is svn trunk at https://sourceforge.net/p/simpleweb/svn/HEAD/tree/

@ngallagher I reported issues I found at https://sourceforge.net/p/simpleweb/bugs/43/ and
https://sourceforge.net/p/simpleweb/bugs/44/. 43 has patch attached, not sure why 44 doesn't, but diffing simple-5.1.7.1-sources.itkach.jar and svn trunk should show the changes. 

Looks like the project is now on Github: https://github.com/ngallagher/simpleframework, but all the stuff from SourceForge was left behind.

**Comment by UnderSampled** [comment]
I saw your sources.itkach.jar file, but didn't know how to compile it again myself. If there's a simple way to convert from that to a compiled version, I would just go ahead and add that to the build script for F-Droid.

**Comment by itkach** [comment]
> but didn't know how to compile it again myself

This should work - grab https://sourceforge.net/p/simpleweb/svn/HEAD/tree/trunk/simple/, replace source in src/main/java/ with source from simple-5.1.7.1-sources.itkach.jar, build with Maven

**Comment by dimqua** [comment]
@UnderSampled Any news associated with this issue?
